name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  publish:
    needs: build
    runs-on: windows-2022

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: .

      - name: Copy build artifacts (skip signing)
        run: |
          # Use unsigned build artifacts directly, skip signing

      - name: Fetch distro branch
        uses: actions/checkout@v4
        with:
          ref: distro
          fetch-depth: 0
          path: distro

      - name: Make setup installer & portable app
        run: |
          # Debug: List directory structure
          Write-Host "Current directory contents:"
          Get-ChildItem -Recurse | Format-Table Name, FullName
          
          mkdir distro\publish
          
          # Find the correct path for build artifacts
          if (Test-Path "app\bin\*") {
            $sourcePath = "app\bin\*"
          } elseif (Test-Path "bin\*") {
            $sourcePath = "bin\*"
          } else {
            Write-Host "Build artifacts not found in expected locations"
            exit 1
          }
          
          Write-Host "Using source path: $sourcePath"
          Compress-Archive -Path $sourcePath -DestinationPath distro\publish\portable.zip -Force
          
          # Copy files to the location expected by setup.iss
          mkdir bin
          Copy-Item -Path $sourcePath -Destination "bin\" -Recurse -Force
          cd distro
          & "$env:ProgramFiles (x86)\Inno Setup 6\iscc.exe" setup.iss

      - name: Upload installer output
        uses: actions/upload-artifact@v4
        id: artifact-upload-installer-step
        with:
          name: setup-installer
          path: |
            distro/out/*.exe

      - name: Copy installer to publish directory (skip signing)
        run: |
          # Skip installer signing, copy directly to publish directory
          Copy-Item -Path "distro\out\*" -Destination "distro\publish\" -Recurse -Force

      - name: Delete unwanted artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: "*"

      - name: Upload unsigned output
        uses: actions/upload-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact-name }}
          path: distro/publish/
